package com.kevin.adsprovider.Data;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "products")
public class Product {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String price;

    @DynamoDBAttribute
    private String brand;

    @DynamoDBAttribute
    private String imgUrl;

    @DynamoDBAttribute
    private String productName;
}
